title: Blog de Programadora
author: fabiana oliveira
email: fabiana.rr.oliveira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Olá, me chamo Fabiana Oliveira, sou estudante em Análise e Desenvolvimento de Sistemas 
  e este é um blog de estudo e pessoal usando a ferramenta jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: __hibhaaf
github_username:  faahbih

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
permalink: /:title
exclude:
  # - Gemfile
  # - Gemfile.lock


